name: CI

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: OTP-${{matrix.otp}}, OS-${{matrix.os}}
    runs-on: ${{matrix.os}}
    services:
      cassandra:
        image: cassandra:4
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 20
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-22.04"
        otp:
          - "26.2"
          - "25.3"
          - "24.3"
        rebar3:
          - "3.20.0"

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Cassandra Tables
        run: "docker exec ${{ job.services.cassandra.id }} cqlsh -u cassandra -p cassandra --debug localhost 9042 --execute=\"CREATE KEYSPACE IF NOT EXISTS test WITH REPLICATION = {'class': 'SimpleStrategy', 'replication_factor': '1'};CREATE TABLE test.tab (first_id bigint, second_id text, col_text text, col_map map<text, text>, PRIMARY KEY (first_id, second_id));DESC keyspaces;\""

      - uses: erlef/setup-beam@2f0cc07b4b9bea248ae098aba9e1a8a1de5ec24c # v1.17.5
        with:
          otp-version: ${{matrix.otp}}
          rebar3-version: ${{ matrix.rebar3 }}

      - name: Common test, eunit, coverage
        run: make tests
